GET localhost:8080/api/scenes

###
GET http://localhost:8080/api/scenes/directions/1


###
POST http://localhost:8080/api/scenes
Content-Type: application/json

{
  "id": 5,
  "image": null,
  "description": "This is another description"
}
