### Get all Scenes
GET localhost:8080/api/scenes

### Get Scene by Id
GET http://localhost:8080/api/scenes/1



### Save Scene
POST http://localhost:8080/api/scenes
Content-Type: application/json

{
  "image": null,
  "description": "This is another description"
}


### Modify Scene
PUT http://localhost:8080/api/scenes/1
Content-Type: application/json

{
  "image": null,
  "description": "This is a new description."
}

### Delete Scene
DELETE http://localhost:8080/api/scenes/1


### Get directions
GET http://localhost:8080/api/scenes/directions/1
